SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
CREATE DATABASE IF NOT EXISTS `devstore` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `devstore`;

CREATE TABLE IF NOT EXISTS `users` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`uuid` VARCHAR(36) NOT NULL,`email` VARCHAR(128) DEFAULT NULL,`mobile` VARCHAR(32) DEFAULT NULL,`nickname` VARCHAR(64) NOT NULL,`avatar` VARCHAR(255) DEFAULT '',`status` TINYINT NOT NULL DEFAULT 1,`source` VARCHAR(32) NOT NULL DEFAULT 'local',`last_login_at` DATETIME DEFAULT NULL,`last_login_ip` VARCHAR(64) DEFAULT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`deleted_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `uk_users_uuid` (`uuid`),UNIQUE KEY `uk_users_email` (`email`),UNIQUE KEY `uk_users_mobile` (`mobile`),KEY `idx_users_status` (`status`),KEY `idx_users_created_at` (`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
CREATE TABLE IF NOT EXISTS `user_profiles` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`user_id` BIGINT UNSIGNED NOT NULL,`bio` VARCHAR(255) DEFAULT '',`github` VARCHAR(255) DEFAULT '',`company` VARCHAR(128) DEFAULT '',`position` VARCHAR(128) DEFAULT '',`city` VARCHAR(128) DEFAULT '',`gender` TINYINT NOT NULL DEFAULT 0,`birthday` DATE DEFAULT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_user_profiles_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户资料';
CREATE TABLE IF NOT EXISTS `user_auths` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`user_id` BIGINT UNSIGNED NOT NULL,`auth_type` VARCHAR(32) NOT NULL,`identifier` VARCHAR(128) NOT NULL,`credential` VARCHAR(255) NOT NULL,`verified` TINYINT NOT NULL DEFAULT 0,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_user_auths_type_identifier` (`auth_type`,`identifier`),KEY `idx_user_auths_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户认证凭证';
CREATE TABLE IF NOT EXISTS `oauth_bindings` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`user_id` BIGINT UNSIGNED NOT NULL,`provider` VARCHAR(32) NOT NULL,`provider_user_id` VARCHAR(128) NOT NULL,`provider_username` VARCHAR(128) DEFAULT '',`access_token` TEXT,`refresh_token` TEXT,`expires_at` DATETIME DEFAULT NULL,`raw_profile` JSON DEFAULT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_oauth_bindings_provider_uid` (`provider`,`provider_user_id`),KEY `idx_oauth_bindings_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='第三方绑定';
CREATE TABLE IF NOT EXISTS `user_balance_accounts` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`user_id` BIGINT UNSIGNED NOT NULL,`balance` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`frozen_balance` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`version` BIGINT NOT NULL DEFAULT 0,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_user_balance_accounts_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='余额账户';
CREATE TABLE IF NOT EXISTS `user_balance_flows` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`user_id` BIGINT UNSIGNED NOT NULL,`biz_type` VARCHAR(32) NOT NULL,`biz_no` VARCHAR(64) NOT NULL,`direction` TINYINT NOT NULL,`amount` DECIMAL(18,2) NOT NULL,`balance_after` DECIMAL(18,2) NOT NULL,`remark` VARCHAR(255) DEFAULT '',`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_user_balance_flows_biz` (`biz_type`,`biz_no`,`user_id`),KEY `idx_user_balance_flows_user_id` (`user_id`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='余额流水';
CREATE TABLE IF NOT EXISTS `user_points_accounts` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`user_id` BIGINT UNSIGNED NOT NULL,`points` BIGINT NOT NULL DEFAULT 0,`total_points` BIGINT NOT NULL DEFAULT 0,`used_points` BIGINT NOT NULL DEFAULT 0,`version` BIGINT NOT NULL DEFAULT 0,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_user_points_accounts_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分账户';
CREATE TABLE IF NOT EXISTS `user_points_flows` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`user_id` BIGINT UNSIGNED NOT NULL,`biz_type` VARCHAR(32) NOT NULL,`biz_no` VARCHAR(64) NOT NULL,`direction` TINYINT NOT NULL,`points` BIGINT NOT NULL,`points_after` BIGINT NOT NULL,`remark` VARCHAR(255) DEFAULT '',`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_user_points_flows_biz` (`biz_type`,`biz_no`,`user_id`),KEY `idx_user_points_flows_user_id` (`user_id`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分流水';
CREATE TABLE IF NOT EXISTS `user_sign_records` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`user_id` BIGINT UNSIGNED NOT NULL,`sign_date` DATE NOT NULL,`streak_days` INT NOT NULL DEFAULT 1,`reward_points` BIGINT NOT NULL DEFAULT 0,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_user_sign_records_user_day` (`user_id`,`sign_date`),KEY `idx_user_sign_records_user_id` (`user_id`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='签到记录';
CREATE TABLE IF NOT EXISTS `categories` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`parent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,`name` VARCHAR(64) NOT NULL,`icon` VARCHAR(255) DEFAULT '',`sort` INT NOT NULL DEFAULT 0,`status` TINYINT NOT NULL DEFAULT 1,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),KEY `idx_categories_parent_id` (`parent_id`,`sort`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分类';
CREATE TABLE IF NOT EXISTS `products` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`category_id` BIGINT UNSIGNED NOT NULL,`name` VARCHAR(128) NOT NULL,`subtitle` VARCHAR(255) DEFAULT '',`type` VARCHAR(32) NOT NULL DEFAULT 'normal',`status` TINYINT NOT NULL DEFAULT 1,`cover` VARCHAR(255) DEFAULT '',`album` JSON DEFAULT NULL,`description` MEDIUMTEXT,`tags` JSON DEFAULT NULL,`price` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`origin_price` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`points_price` BIGINT NOT NULL DEFAULT 0,`sales_count` BIGINT NOT NULL DEFAULT 0,`view_count` BIGINT NOT NULL DEFAULT 0,`stock` BIGINT NOT NULL DEFAULT 0,`lock_stock` BIGINT NOT NULL DEFAULT 0,`limit_per_user` INT NOT NULL DEFAULT 0,`is_hot` TINYINT NOT NULL DEFAULT 0,`is_recommend` TINYINT NOT NULL DEFAULT 0,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`deleted_at` DATETIME DEFAULT NULL,PRIMARY KEY (`id`),KEY `idx_products_category_id` (`category_id`),KEY `idx_products_type_status` (`type`,`status`),KEY `idx_products_hot` (`is_hot`,`is_recommend`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品';
CREATE TABLE IF NOT EXISTS `product_skus` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`product_id` BIGINT UNSIGNED NOT NULL,`sku_code` VARCHAR(64) NOT NULL,`title` VARCHAR(128) NOT NULL,`specs` JSON DEFAULT NULL,`price` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`points_price` BIGINT NOT NULL DEFAULT 0,`stock` BIGINT NOT NULL DEFAULT 0,`lock_stock` BIGINT NOT NULL DEFAULT 0,`status` TINYINT NOT NULL DEFAULT 1,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_product_skus_sku_code` (`sku_code`),KEY `idx_product_skus_product_id` (`product_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SKU';
CREATE TABLE IF NOT EXISTS `product_images` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`product_id` BIGINT UNSIGNED NOT NULL,`image_url` VARCHAR(255) NOT NULL,`sort` INT NOT NULL DEFAULT 0,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`),KEY `idx_product_images_product_id` (`product_id`,`sort`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品图片';
CREATE TABLE IF NOT EXISTS `inventories` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`product_id` BIGINT UNSIGNED NOT NULL,`sku_id` BIGINT UNSIGNED NOT NULL,`total_stock` BIGINT NOT NULL DEFAULT 0,`available_stock` BIGINT NOT NULL DEFAULT 0,`reserved_stock` BIGINT NOT NULL DEFAULT 0,`version` BIGINT NOT NULL DEFAULT 0,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_inventories_sku_id` (`sku_id`),KEY `idx_inventories_product_id` (`product_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存';
CREATE TABLE IF NOT EXISTS `carts` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`user_id` BIGINT UNSIGNED NOT NULL,`status` TINYINT NOT NULL DEFAULT 1,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_carts_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='购物车';
CREATE TABLE IF NOT EXISTS `cart_items` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`cart_id` BIGINT UNSIGNED NOT NULL,`user_id` BIGINT UNSIGNED NOT NULL,`product_id` BIGINT UNSIGNED NOT NULL,`sku_id` BIGINT UNSIGNED NOT NULL,`quantity` INT NOT NULL,`checked` TINYINT NOT NULL DEFAULT 1,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_cart_items_user_sku` (`user_id`,`sku_id`),KEY `idx_cart_items_cart_id` (`cart_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='购物车商品';
CREATE TABLE IF NOT EXISTS `orders` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`order_no` VARCHAR(64) NOT NULL,`user_id` BIGINT UNSIGNED NOT NULL,`order_type` VARCHAR(32) NOT NULL DEFAULT 'normal',`status` TINYINT NOT NULL DEFAULT 10,`total_amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`discount_amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`pay_amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`points_amount` BIGINT NOT NULL DEFAULT 0,`coupon_id` BIGINT UNSIGNED DEFAULT NULL,`campaign_id` BIGINT UNSIGNED DEFAULT NULL,`remark` VARCHAR(255) DEFAULT '',`submit_token` VARCHAR(64) DEFAULT '',`pay_deadline_at` DATETIME DEFAULT NULL,`paid_at` DATETIME DEFAULT NULL,`closed_at` DATETIME DEFAULT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_orders_order_no` (`order_no`),UNIQUE KEY `uk_orders_submit_token` (`submit_token`),KEY `idx_orders_user_id_status` (`user_id`,`status`,`created_at`),KEY `idx_orders_campaign_id` (`campaign_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单';
CREATE TABLE IF NOT EXISTS `order_items` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`order_id` BIGINT UNSIGNED NOT NULL,`order_no` VARCHAR(64) NOT NULL,`user_id` BIGINT UNSIGNED NOT NULL,`product_id` BIGINT UNSIGNED NOT NULL,`sku_id` BIGINT UNSIGNED NOT NULL,`product_name` VARCHAR(128) NOT NULL,`sku_title` VARCHAR(128) NOT NULL,`cover` VARCHAR(255) DEFAULT '',`price` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`points_price` BIGINT NOT NULL DEFAULT 0,`quantity` INT NOT NULL DEFAULT 1,`total_amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`),KEY `idx_order_items_order_id` (`order_id`),KEY `idx_order_items_user_id` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单项';
CREATE TABLE IF NOT EXISTS `payment_orders` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`pay_no` VARCHAR(64) NOT NULL,`order_no` VARCHAR(64) NOT NULL,`user_id` BIGINT UNSIGNED NOT NULL,`pay_type` VARCHAR(32) NOT NULL DEFAULT 'balance',`status` TINYINT NOT NULL DEFAULT 10,`amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`idempotent_key` VARCHAR(64) DEFAULT '',`paid_at` DATETIME DEFAULT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_payment_orders_pay_no` (`pay_no`),UNIQUE KEY `uk_payment_orders_idempotent_key` (`idempotent_key`),KEY `idx_payment_orders_order_no` (`order_no`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付单';
CREATE TABLE IF NOT EXISTS `payment_flows` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`pay_no` VARCHAR(64) NOT NULL,`order_no` VARCHAR(64) NOT NULL,`user_id` BIGINT UNSIGNED NOT NULL,`third_party_no` VARCHAR(128) DEFAULT '',`channel` VARCHAR(32) NOT NULL DEFAULT 'mock',`event_type` VARCHAR(32) NOT NULL,`raw_payload` JSON DEFAULT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`),KEY `idx_payment_flows_pay_no` (`pay_no`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付流水';
CREATE TABLE IF NOT EXISTS `announcements` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`title` VARCHAR(80) NOT NULL,`content` VARCHAR(500) NOT NULL,`link` VARCHAR(255) DEFAULT '',`level` VARCHAR(16) NOT NULL DEFAULT 'info',`sort` INT NOT NULL DEFAULT 0,`pinned` TINYINT NOT NULL DEFAULT 0,`status` TINYINT NOT NULL DEFAULT 1,`start_at` DATETIME DEFAULT NULL,`end_at` DATETIME DEFAULT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),KEY `idx_announcements_status` (`status`,`pinned`,`sort`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公告';
CREATE TABLE IF NOT EXISTS `user_wishlists` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`user_id` BIGINT UNSIGNED NOT NULL,`product_id` BIGINT UNSIGNED NOT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_user_wishlists_user_product` (`user_id`,`product_id`),KEY `idx_user_wishlists_product` (`product_id`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品心愿单';
CREATE TABLE IF NOT EXISTS `delivery_records` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`order_no` VARCHAR(64) NOT NULL,`order_item_id` BIGINT UNSIGNED NOT NULL,`user_id` BIGINT UNSIGNED NOT NULL,`product_id` BIGINT UNSIGNED NOT NULL,`sku_id` BIGINT UNSIGNED NOT NULL,`delivery_type` VARCHAR(32) NOT NULL DEFAULT 'auto',`content` TEXT,`status` TINYINT NOT NULL DEFAULT 20,`delivered_at` DATETIME DEFAULT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),KEY `idx_delivery_records_order_no` (`order_no`,`created_at`),KEY `idx_delivery_records_user_id` (`user_id`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='虚拟发货记录';
CREATE TABLE IF NOT EXISTS `order_logs` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`order_no` VARCHAR(64) NOT NULL,`status_from` TINYINT DEFAULT NULL,`status_to` TINYINT NOT NULL,`operator_type` VARCHAR(32) NOT NULL,`operator_id` BIGINT UNSIGNED DEFAULT NULL,`remark` VARCHAR(255) DEFAULT '',`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`),KEY `idx_order_logs_order_no` (`order_no`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单日志';
CREATE TABLE IF NOT EXISTS `coupon_templates` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(128) NOT NULL,`type` VARCHAR(32) NOT NULL DEFAULT 'full_reduction',`total` INT NOT NULL DEFAULT 0,`issued` INT NOT NULL DEFAULT 0,`amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`threshold_amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`points_cost` BIGINT NOT NULL DEFAULT 0,`status` TINYINT NOT NULL DEFAULT 1,`start_at` DATETIME NOT NULL,`end_at` DATETIME NOT NULL,`description` VARCHAR(255) DEFAULT '',`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),KEY `idx_coupon_templates_status_time` (`status`,`start_at`,`end_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='券模板';
CREATE TABLE IF NOT EXISTS `coupons` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`template_id` BIGINT UNSIGNED NOT NULL,`name` VARCHAR(128) NOT NULL,`code` VARCHAR(64) NOT NULL,`status` TINYINT NOT NULL DEFAULT 1,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_coupons_code` (`code`),KEY `idx_coupons_template_id` (`template_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='券实例';
CREATE TABLE IF NOT EXISTS `user_coupons` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`user_id` BIGINT UNSIGNED NOT NULL,`template_id` BIGINT UNSIGNED NOT NULL,`coupon_code` VARCHAR(64) NOT NULL,`status` TINYINT NOT NULL DEFAULT 10,`received_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`used_at` DATETIME DEFAULT NULL,`expired_at` DATETIME NOT NULL,`order_no` VARCHAR(64) DEFAULT '',PRIMARY KEY (`id`),UNIQUE KEY `uk_user_coupons_code` (`coupon_code`),KEY `idx_user_coupons_user_id_status` (`user_id`,`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户券';
CREATE TABLE IF NOT EXISTS `campaigns` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(128) NOT NULL,`type` VARCHAR(32) NOT NULL DEFAULT 'discount',`status` TINYINT NOT NULL DEFAULT 1,`start_at` DATETIME NOT NULL,`end_at` DATETIME NOT NULL,`banner` VARCHAR(255) DEFAULT '',`rules` JSON DEFAULT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),KEY `idx_campaigns_type_status` (`type`,`status`,`start_at`,`end_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动';
CREATE TABLE IF NOT EXISTS `seckill_campaigns` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`campaign_id` BIGINT UNSIGNED NOT NULL,`name` VARCHAR(128) NOT NULL,`status` TINYINT NOT NULL DEFAULT 1,`start_at` DATETIME NOT NULL,`end_at` DATETIME NOT NULL,`warmup_at` DATETIME DEFAULT NULL,`limit_per_user` INT NOT NULL DEFAULT 1,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),KEY `idx_seckill_campaigns_campaign_id` (`campaign_id`),KEY `idx_seckill_campaigns_status_time` (`status`,`start_at`,`end_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='秒杀活动';
CREATE TABLE IF NOT EXISTS `seckill_goods` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`seckill_campaign_id` BIGINT UNSIGNED NOT NULL,`product_id` BIGINT UNSIGNED NOT NULL,`sku_id` BIGINT UNSIGNED NOT NULL,`seckill_price` DECIMAL(18,2) NOT NULL DEFAULT 0.00,`stock` BIGINT NOT NULL DEFAULT 0,`available_stock` BIGINT NOT NULL DEFAULT 0,`locked_stock` BIGINT NOT NULL DEFAULT 0,`status` TINYINT NOT NULL DEFAULT 1,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_seckill_goods_campaign_sku` (`seckill_campaign_id`,`sku_id`),KEY `idx_seckill_goods_product_id` (`product_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='秒杀商品';
CREATE TABLE IF NOT EXISTS `admin_users` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`username` VARCHAR(64) NOT NULL,`password` VARCHAR(255) NOT NULL,`nickname` VARCHAR(64) NOT NULL,`status` TINYINT NOT NULL DEFAULT 1,`last_login_at` DATETIME DEFAULT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_admin_users_username` (`username`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管理员';
CREATE TABLE IF NOT EXISTS `admin_roles` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`name` VARCHAR(64) NOT NULL,`code` VARCHAR(64) NOT NULL,`status` TINYINT NOT NULL DEFAULT 1,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_admin_roles_code` (`code`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='后台角色';
CREATE TABLE IF NOT EXISTS `admin_role_permissions` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`role_id` BIGINT UNSIGNED NOT NULL,`permission_code` VARCHAR(128) NOT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_admin_role_permissions` (`role_id`,`permission_code`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色权限';
CREATE TABLE IF NOT EXISTS `operation_logs` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`operator_id` BIGINT UNSIGNED DEFAULT NULL,`operator_type` VARCHAR(32) NOT NULL,`module` VARCHAR(64) NOT NULL,`action` VARCHAR(64) NOT NULL,`biz_no` VARCHAR(64) DEFAULT '',`method` VARCHAR(16) NOT NULL,`path` VARCHAR(255) NOT NULL,`ip` VARCHAR(64) DEFAULT '',`request_body` JSON DEFAULT NULL,`response_body` JSON DEFAULT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`),KEY `idx_operation_logs_module` (`module`,`action`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志';
CREATE TABLE IF NOT EXISTS `mq_consume_logs` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`message_id` VARCHAR(64) NOT NULL,`consumer` VARCHAR(128) NOT NULL,`biz_key` VARCHAR(128) DEFAULT '',`status` TINYINT NOT NULL DEFAULT 10,`retry_count` INT NOT NULL DEFAULT 0,`error_msg` VARCHAR(255) DEFAULT '',`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_mq_consume_logs_message_consumer` (`message_id`,`consumer`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='MQ消费日志';
CREATE TABLE IF NOT EXISTS `idempotent_records` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`idempotent_key` VARCHAR(128) NOT NULL,`biz_type` VARCHAR(32) NOT NULL,`biz_no` VARCHAR(64) DEFAULT '',`status` TINYINT NOT NULL DEFAULT 10,`expired_at` DATETIME DEFAULT NULL,`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY (`id`),UNIQUE KEY `uk_idempotent_records_key` (`idempotent_key`),KEY `idx_idempotent_records_biz` (`biz_type`,`biz_no`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='幂等记录';

INSERT INTO `admin_roles` (`id`,`name`,`code`,`status`) VALUES (1,'超级管理员','super_admin',1) ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
INSERT INTO `admin_users` (`id`,`username`,`password`,`nickname`,`status`) VALUES (1,'admin','$2a$10$8HFhcK2mHL3daxrgNjNfluWxf0RsDkJx/qgkWNyFIkEoVY38dRcna','系统管理员',1) ON DUPLICATE KEY UPDATE `nickname`=VALUES(`nickname`);
INSERT INTO `users` (`id`,`uuid`,`email`,`nickname`,`avatar`,`status`,`source`) VALUES (1,'00000000-0000-0000-0000-000000000001','demo@devstore.local','DemoUser','',1,'admin_seed') ON DUPLICATE KEY UPDATE `nickname`=VALUES(`nickname`);
INSERT INTO `user_auths` (`id`,`user_id`,`auth_type`,`identifier`,`credential`,`verified`) VALUES (1,1,'password','demo@devstore.local','$2a$10$8HFhcK2mHL3daxrgNjNfluWxf0RsDkJx/qgkWNyFIkEoVY38dRcna',1) ON DUPLICATE KEY UPDATE `verified`=VALUES(`verified`);
INSERT INTO `user_balance_accounts` (`user_id`,`balance`,`frozen_balance`,`version`) VALUES (1,1000.00,0.00,0) ON DUPLICATE KEY UPDATE `balance`=VALUES(`balance`);
INSERT INTO `user_points_accounts` (`user_id`,`points`,`total_points`,`used_points`,`version`) VALUES (1,5000,5000,0,0) ON DUPLICATE KEY UPDATE `points`=VALUES(`points`);
INSERT INTO `user_balance_accounts` (`user_id`,`balance`,`frozen_balance`,`version`) SELECT u.id,0.00,0.00,0 FROM `users` u LEFT JOIN `user_balance_accounts` uba ON uba.user_id = u.id WHERE uba.user_id IS NULL;
INSERT INTO `user_points_accounts` (`user_id`,`points`,`total_points`,`used_points`,`version`) SELECT u.id,0,0,0,0 FROM `users` u LEFT JOIN `user_points_accounts` upa ON upa.user_id = u.id WHERE upa.user_id IS NULL;
INSERT INTO `announcements` (`id`,`title`,`content`,`link`,`level`,`sort`,`pinned`,`status`) VALUES
(1,'欢迎来到 DevStore','全站虚拟商品已升级为真实下单与自动发货流程，支付后可在订单详情查看交付内容。','/products','success',100,1,1),
(2,'每日签到奖励','每日签到奖励已同步进入钱包余额与积分账户，连续签到会有额外奖励。','/user/sign','info',90,0,1)
ON DUPLICATE KEY UPDATE `content` = VALUES(`content`);

SET FOREIGN_KEY_CHECKS = 1;
INSERT INTO `categories` (`id`,`parent_id`,`name`,`icon`,`sort`,`status`) VALUES
(1,0,'技术图书','book',100,1),
(2,0,'活动票务','ticket',90,1),
(3,0,'积分专区','points',80,1)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

INSERT INTO `products` (`id`,`category_id`,`name`,`subtitle`,`type`,`status`,`cover`,`description`,`price`,`origin_price`,`points_price`,`sales_count`,`view_count`,`stock`,`lock_stock`,`limit_per_user`,`is_hot`,`is_recommend`)
VALUES
(1,1,'Go 并发深潜专栏','适合中高级 Go 开发者的高并发实践专栏','normal',1,'https://images.unsplash.com/photo-1515879218367-8466d910aaa4','围绕 goroutine 调度、内存模型、锁竞争与性能优化展开。',69.00,99.00,0,128,560,256,0,0,1,1),
(2,2,'开发者线下大会门票','含主论坛与实践工作坊通票','limited',1,'https://images.unsplash.com/photo-1498050108023-c5249f4df085','支持余额支付、优惠券满减与限时活动。',299.00,399.00,0,86,420,80,0,2,1,1),
(3,3,'积分兑换机械键盘券','连续签到和支付奖励积分可直接兑换','points',1,'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae','高价值开发者周边兑换券。',0.00,0.00,5800,42,190,60,0,1,0,1)
ON DUPLICATE KEY UPDATE `subtitle` = VALUES(`subtitle`);

INSERT INTO `product_skus` (`id`,`product_id`,`sku_code`,`title`,`price`,`points_price`,`stock`,`lock_stock`,`status`) VALUES
(1,1,'GO-BOOK-001','默认规格',69.00,0,256,0,1),
(2,2,'DEVCONF-2026','大会通票',299.00,0,80,0,1),
(3,3,'POINTS-KB-001','兑换券标准版',0.00,5800,60,0,1)
ON DUPLICATE KEY UPDATE `title` = VALUES(`title`);

INSERT INTO `inventories` (`id`,`product_id`,`sku_id`,`total_stock`,`available_stock`,`reserved_stock`,`version`) VALUES
(1,1,1,256,256,0,0),
(2,2,2,80,80,0,0),
(3,3,3,60,60,0,0)
ON DUPLICATE KEY UPDATE `total_stock` = VALUES(`total_stock`);
INSERT INTO `campaigns` (`id`,`name`,`type`,`status`,`start_at`,`end_at`,`banner`,`rules`) VALUES
(1,'周末秒杀专场','seckill',1,'2026-03-20 20:00:00','2026-03-27 23:59:59','',JSON_OBJECT('limit_per_user',1))
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

INSERT INTO `seckill_campaigns` (`id`,`campaign_id`,`name`,`status`,`start_at`,`end_at`,`warmup_at`,`limit_per_user`) VALUES
(1,1,'周末秒杀专场',1,'2026-03-20 20:00:00','2026-03-27 23:59:59','2026-03-20 19:30:00',1)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

INSERT INTO `seckill_goods` (`id`,`seckill_campaign_id`,`product_id`,`sku_id`,`seckill_price`,`stock`,`available_stock`,`locked_stock`,`status`) VALUES
(1,1,2,2,9.90,30,30,0,1)
ON DUPLICATE KEY UPDATE `seckill_price` = VALUES(`seckill_price`);
INSERT INTO `coupon_templates` (`id`,`name`,`type`,`total`,`issued`,`amount`,`threshold_amount`,`points_cost`,`status`,`start_at`,`end_at`,`description`) VALUES
(1,'新人满减券','full_reduction',1000,0,20.00,99.00,0,1,'2026-03-01 00:00:00','2026-12-31 23:59:59','新人注册礼包'),
(2,'活动中心专享券','full_reduction',500,0,50.00,299.00,0,1,'2026-03-01 00:00:00','2026-12-31 23:59:59','活动商品专享')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

